controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Usuarios;
use app\models\Grupos;
use app\models\Mensajes;
use app\models\Prioridades;
use app\models\Reciben;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout','admin'],
                'rules' => [
                    [
                        'actions' => ['logout','admin'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            Yii::$app->user->identity->recibirMensajes();
            if (Yii::$app->user->identity->isAdmin()){
                return $this->redirect('admin');
            }else{
                return $this->redirect(
                    [
                        'usuarios/escritorio', 
                        'id'=> Yii::$app->user->identity->id
                    ]);
            }
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        Yii::$app->session->set('escritorio','nuevo');

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAyuda()
    {
        return $this->render('ayuda');
    }

    public function actionAdmin()
    {
        if (Yii::$app->user->identity->isAdmin()){
            $searchUsuario = new Usuarios();
            $dataProviderUsuarios = $searchUsuario->search(Yii::$app->request->queryParams);
            $dataProviderUsuarios->setSort([
                    'attributes'=>[
                        'activo' =>[
                            'default' => SORT_ASC
                        ]
                    ]
                ]);
            $searchGrupo = new Grupos();
            $dataProviderGrupos = $searchGrupo->search(Yii::$app->request->queryParams);

            $searchMensaje = new Mensajes();
            $dataProviderMensajes = $searchMensaje->search(Yii::$app->request->queryParams);

            $usuario = Yii::$app->user->identity;

            $remitentes = implode(',', array_unique(ArrayHelper::map(
                $usuario->getRecibens()->where(['fecha_leido'=>null])->all(),
                'id_mensaje','mensaje.origen.nombre')));
            $no_activos_nombres = implode(',', ArrayHelper::map(
                Usuarios::find()->where(['activo'=>0])->all(),
                'id_usuario','nombre'));

            $usuarios_totales = Usuarios::find()->count();
            $usuarios_no_activos = Usuarios::find()->where(['activo'=>0])->count();
            $mensajes_totales = Mensajes::find()->count();
            $mensajes_no_leidos = Reciben::find()->where(['fecha_leido'=>null])->count();

            return $this->render('admin',[
                'dataProviderUsuarios' => $dataProviderUsuarios,
                'searchUsuario' => $searchUsuario,
                'dataProviderGrupos' =>$dataProviderGrupos,
                'searchGrupo' => $searchGrupo,
                'dataProviderMensajes' =>$dataProviderMensajes,
                'searchMensaje' => $searchMensaje,
                'usuario' => $usuario,
                'mensajes_sin_leer' => $usuario->mensajesSinLeer(),
                'remitentes' => $remitentes,
                'usuarios_totales' => $usuarios_totales,
                'usuarios_no_activos' => $usuarios_no_activos,
                'mensajes_totales' => $mensajes_totales,
                'mensajes_no_leidos' => $mensajes_no_leidos,
                'no_activos_nombres' => $no_activos_nombres,
            ]);
        }
        return $this->goHome();
    }

}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            !Yii::$app->user->isGuest 
                ? (Yii::$app->user->identity->isAdmin() ? (
                    ['label' => 'Administración', 'url' => ['site/admin']]) : '' ) 
                : '',
            !Yii::$app->user->isGuest 
                ? ( ['label' => 'Escritorio', 'url' => ['usuarios/escritorio', 'id'=>Yii::$app->user->id]] ):'',
            ['label' => 'Ayuda', 'url' => ['/site/ayuda']],
            ['label' => 'Contacto', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Acceso', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Salir (' . Yii::$app->user->identity->login . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="text-center">&copy; Mercurio <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>