controllers/GruposController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Grupos;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GruposController implements the CRUD actions for Grupos model.
 */
class GruposController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [
                    'create',
                    'delete',
                    'update',
                    'view',
                ],
                'rules' => [
                    [
                        'actions' => [],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => [],
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    protected function hasAccess($id){
        return (Yii::$app->user->identity->id == $id 
            || Yii::$app->user->identity->isAdmin());
    }

    protected function isAdmin(){
        return Yii::$app->user->identity->isAdmin();
    }
    /**
     * Lists all Grupos models.
     * @return mixed
     */
    /*public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Grupos::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }*/

    /**
     * Displays a single Grupos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Grupos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Grupos();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_grupo]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    
   /* public function actionAdd()
    {
        if ($id = Yii::$app->request->post('id')){
            $participan = new Participan();
            $participan->id_grupo = $id;
            $participan->id_usuario = Yii::$app->request->post('usuario');
            $participan->save(false);
            return $this->goBack();
        }
        
        $usuario = Yii::$app->request->get('id_usuario');
        $grupos = ArrayHelper::map(Grupos::find()->all(), 'id_grupo', 'grupo');

        return $this->render('add', [
            'grupos' => $grupos,
            'usuario' => $usuario
        ]);
   }*/

    /**
     * Updates an existing Grupos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if($this->isAdmin()){
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id_grupo]);
            }

            return $this->render('update', [
                'model' => $model,
            ]);
        }else{
            return $this->goHome();
        }
    }

    /**
     * Deletes an existing Grupos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if($this->isAdmin()){
            $this->findModel($id)->delete();

            return $this->redirect(['index']);
        }else{
            return $this->goHome();
        }
    }

    /**
     * Finds the Grupos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Grupos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Grupos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('Este grupo no existe.');
    }
}

controllers/MensajesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Mensajes;
use app\models\Reciben;
use app\models\Prioridades;
use app\models\Usuarios;
use yii\filters\AccessControl;
use app\models\Grupos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * MensajesController implements the CRUD actions for Mensajes model.
 */
class MensajesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [
                    'create',
                    'delete',
                    'leer',
                    'update',
                    'view'
                ],
                'rules' => [
                    [
                        'actions' => [],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => [],
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    protected function hasAccess($id){
        return (Yii::$app->user->identity->id == $id 
            || Yii::$app->user->identity->isAdmin());
    }

    protected function isAdmin(){
        return Yii::$app->user->identity->isAdmin();
    }
    /**
     * Lists all Mensajes models.
     * @return mixed
     */
    /*public function actionIndex()
    {

        $dataProvider = new ActiveDataProvider([
            'query' => Mensajes::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }*/

    /**
     * Displays a single Mensajes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        if ($this->hasAccess($id)){
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }else{
            return $this->goHome();
        }
    }

    /**
     * Creates a new Mensajes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Mensajes();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('mensajeEnviado');
            if (isset($_GET['destino'])){
                $destino = Usuarios::find()
                    ->where(['id_usuario'=>$_GET['destino'],'activo'=>1])
                    ->one();
                $model->enviar([$destino]);

            }else if(isset($_GET['grupo'])){
                $grupo = Grupos::find()
                    ->where(['id_grupo'=>$_GET['grupo']])
                    ->one();
                $model->enviar($grupo->usuarios);

            }else if(isset($_GET['todos'])){
                if($_GET['todos'] === 'usuarios'){
                    $usuarios = Usuarios::find()
                        ->where(['activo'=>1])
                        ->andWhere(['<>','id_usuario',Yii::$app->user->identity->id])
                        ->all();
                    $model->enviar($usuarios);
                }else if ($_GET['todos'] == 'grupos'){
                    $grupos = Grupos::find()->all();
                    foreach($grupos as $grupo){
                        $model->enviar($grupo->getUsuarios()
                            ->where(['activo'=>1])
                            ->andWhere(['<>','id_usuario',Yii::$app->user->identity->id])
                        );
                    }
                }
            }
            return $this->refresh();
        }

        return $this->render('create', [
            'model' => $model,
            'prioridades'=> ArrayHelper::map(Prioridades::find()->all(), 'prioridad', 'prioridad'),
        ]);
    }

    public function actionLeer($id){
        $mensaje = $this->findModel($id);
        $id_usuario = Yii::$app->user->identity->id;
        $mensaje->getRecibens()->where([
            'id_mensaje' => $id,
            'id_usuario' => $id_usuario
        ])->one()->mensajeLeido();
        return $this->render('leer',[
            'model' => $mensaje
        ]);
    }

    /**
     * Updates an existing Mensajes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if($this->isAdmin()){
            $model = $this->findModel($id);

            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id_mensaje]);
            }

            return $this->render('update', [
                'model' => $model,
            ]);
        }else{
            return $this->goHome();
        }
    }

    /**
     * Deletes an existing Mensajes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        if($this->isAdmin()){
            $this->findModel($id)->delete();

            return $this->redirect(['site/admin']);
        }else{
            return $this->goHome();
        }
    }

    /**
     * Finds the Mensajes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Mensajes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Mensajes::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('El mensaje solicitado no existe.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Usuarios;
use app\models\Grupos;
use app\models\Mensajes;
use app\models\Prioridades;
use app\models\Reciben;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout','admin'],
                'rules' => [
                    [
                        'actions' => ['logout','admin'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            Yii::$app->user->identity->recibirMensajes();
            if (Yii::$app->user->identity->isAdmin()){
                return $this->redirect('admin');
            }else{
                return $this->redirect(
                    [
                        'usuarios/escritorio', 
                        'id'=> Yii::$app->user->identity->id
                    ]);
            }
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        Yii::$app->session->set('escritorio','nuevo');

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAyuda()
    {
        return $this->render('ayuda');
    }

    public function actionAdmin()
    {
        if (Yii::$app->user->identity->isAdmin()){
            $searchUsuario = new Usuarios();
            $dataProviderUsuarios = $searchUsuario->search(Yii::$app->request->queryParams);
            $dataProviderUsuarios->setSort([
                    'attributes'=>[
                        'activo' =>[
                            'default' => SORT_ASC
                        ]
                    ]
                ]);
            $searchGrupo = new Grupos();
            $dataProviderGrupos = $searchGrupo->search(Yii::$app->request->queryParams);

            $searchMensaje = new Mensajes();
            $dataProviderMensajes = $searchMensaje->search(Yii::$app->request->queryParams);

            $usuario = Yii::$app->user->identity;

            $remitentes = implode(',', array_unique(ArrayHelper::map(
                $usuario->getRecibens()->where(['fecha_leido'=>null])->all(),
                'id_mensaje','mensaje.origen.nombre')));
            $no_activos_nombres = implode(',', ArrayHelper::map(
                Usuarios::find()->where(['activo'=>0])->all(),
                'id_usuario','nombre'));

            $usuarios_totales = Usuarios::find()->count();
            $usuarios_no_activos = Usuarios::find()->where(['activo'=>0])->count();
            $mensajes_totales = Mensajes::find()->count();
            $mensajes_no_leidos = Reciben::find()->where(['fecha_leido'=>null])->count();

            return $this->render('admin',[
                'dataProviderUsuarios' => $dataProviderUsuarios,
                'searchUsuario' => $searchUsuario,
                'dataProviderGrupos' =>$dataProviderGrupos,
                'searchGrupo' => $searchGrupo,
                'dataProviderMensajes' =>$dataProviderMensajes,
                'searchMensaje' => $searchMensaje,
                'usuario' => $usuario,
                'mensajes_sin_leer' => $usuario->mensajesSinLeer(),
                'remitentes' => $remitentes,
                'usuarios_totales' => $usuarios_totales,
                'usuarios_no_activos' => $usuarios_no_activos,
                'mensajes_totales' => $mensajes_totales,
                'mensajes_no_leidos' => $mensajes_no_leidos,
                'no_activos_nombres' => $no_activos_nombres,
            ]);
        }
        return $this->goHome();
    }

}

views/site/admin.php
<?php


use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use amass\panel\Panel;
use app\models\Usuarios;
use app\models\Mensajes;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Zona administrativa';
?>
    <h1><?= Html::encode($this->title) ?></h1>

<?php 

$content = ($mensajes_sin_leer > 0) 
    ? Html::tag('p', $mensajes_sin_leer . ' mensaje(s) sin leer de '. $remitentes)
    : Html::tag('p', 'No tienen mensajes sin leer.');
$content .= Html::tag(
    'p',
    "Hay <strong>$usuarios_totales</strong> usuarios de los cuales <strong>$usuarios_no_activos</strong> están sin activar: $no_activos_nombres."
);
$content .= Html::tag(
    'p',
    "Hay <strong>$mensajes_totales</strong> mensajes en el sistema de los cuales <strong>$mensajes_no_leidos</strong> están aún sin leer."
);

echo Panel::widget([
    'headerTitle' => 'Información',
    'content' => $content,
    'footer' => false,
    'type' => Panel::TYPE_WARNING,
]);
?>

<div class="row">

<div class="usuarios-index col-xs-12 col-md-9">
<h2>Usuarios</h2>
    <p>
        <?= Html::a('Crear nuevo usuario', ['usuarios/nuevo'], ['class' => 'btn btn-success']) ?>
    </p>

<?php
    Panel::begin([
    'headerTitle' => 'Usuarios',
    'footer' => false,
    'type' => Panel::TYPE_INFO
]); 
    echo GridView::widget([
        'dataProvider' => $dataProviderUsuarios,
        'filterModel' => $searchUsuario,
        'summary' => 'Viendo {begin} - {count} de {totalCount}',
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id_usuario',
            'nombre',
            'email:email',
            'rol',
            'activo',
            [
                'attribute' => 'Grupos',
                'format' => 'text',
                'value' => function($model){
                    return implode(',', ArrayHelper::map($model->grupos,'id_grupo','grupo')); 
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'header' =>'Acciones',
                'template' => '{ver}{modificar}{borrar}{invitar}',
                'buttons' => [
                    'ver' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['usuarios/view', 'id' => $model->id_usuario]);
                    },
                    'modificar' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['usuarios/update', 'id' => $model->id_usuario]);
                    },
                    'borrar' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['usuarios/delete', 'id' => $model->id_usuario], ['data-confirm'=>'¿estás seguro de que quieres borrarlo?','data-method'=>'post']);
                    },
                    'invitar' => function ($url, $model){
                        if ($model->activo === 0){
                            return Html::a('<span class="glyphicon glyphicon-send"></span>', ['usuarios/invitar', 'id'=>$model->id_usuario]);
                        }else{
                            return null;
                        }
                    },
                ],
        ],
        ],
    ]); 
Panel::end();
?>
</div>
<div class="grupos-index col-xs-12 col-md-3">
<h2>Grupos</h2>
    <p>
        <?= Html::a('Crear nuevo grupo', ['grupos/create'], ['class' => 'btn btn-success']) ?>
    </p>

<?php
    Panel::begin([
    'headerTitle' => 'Grupos',
    'footer' => false,
    'type' => Panel::TYPE_INFO
]); 

echo GridView::widget([
        'dataProvider' => $dataProviderGrupos,
        'filterModel' => $searchGrupo,
        'summary' => 'Viendo {begin} - {count} de {totalCount}',
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'grupo',

            [
                'class' => 'yii\grid\ActionColumn',
                'header' =>'Acciones',
                'template' => '{ver}{modificar}{borrar}',
                'buttons' => [
                    'ver' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['grupos/view', 'id' => $model->id_grupo]);
                    },
                    'modificar' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['grupos/update', 'id' => $model->id_grupo]);
                    },
                    'borrar' => function ($url, $model) {

                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['grupos/delete', 'id' => $model->id_grupo], ['data-confirm'=>'¿estás seguro de que quieres borrarlo?','data-method'=>'post']);
                    },
                ],
        ],
        ],
    ]); 
Panel::end();
?>
</div>
</div>
<div class="row">
    <div class="col-xs-12 ">
    <h2>Mensajes</h2>
    <p>
        <?= Html::a('Crear nuevo mensaje', ['mensajes/create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php
    Panel::begin([
    'headerTitle' => 'Mensajes',
    'footer' => false,
    'type' => Panel::TYPE_INFO
]); 
echo GridView::widget([
        'dataProvider' => $dataProviderMensajes,
        'filterModel' => $searchMensaje,
        'summary' => 'Viendo {begin} - {count} de {totalCount}',
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id_mensaje',
            'origen.nombre',
            'contenido',
            'fecha',
            [
                'attribute' => 'Recibens',
                'header' => 'Destino',
                'format' => 'html',
                'value' => function($model){
                    return implode(',', ArrayHelper::map($model->recibens,'id_usuario','usuario.nombre')); 
                }
            ],
            'prioridad',

            [
                'header' => 'Acciones',
                'class' => 'yii\grid\ActionColumn',
                'template' => '{ver}{modificar}{borrar}',
                'buttons' => [
                    'ver' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['mensajes/view', 'id' => $model->id_mensaje]);
                    },
                    'modificar' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['mensajes/update', 'id' => $model->id_mensaje]);
                    },
                    'borrar' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['mensajes/delete', 'id' => $model->id_mensaje], ['data-confirm'=>'¿estás seguro de que quieres borrarlo?','data-method'=>'post']);
                    },
                ],
        ],
        ],
    ]); 
Panel::end();
?>
    </div>
</div>

views/site/ayuda.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\bootstrap\Collapse;

$this->title = 'Ayuda';
?>
<div class="site-about">

    <div class="row">
       <div class="col-md-6 col-md-offset-3">
    <h1><?= Html::encode($this->title) ?></h1>
<?php
echo Collapse::widget([
    'items' => [
        [
            'label' => 'Sobre Mercurio',
            'content' => 'Mercurio, mensajería intranet, es una aplicación que pretende proporcionar un sistema ágil, versátil y fácil de usar para la comunicación entre los usuarios del sistema.',
            'contentOptions' => ['class' => 'in'],
        ],
        [
            'label' => 'Sobre Cómo usar Mercurio',
            'content' => ['Al ser una aplicación exclusivamente interna, no permite el registro sin una invitación previa del administrador de la aplicación.',
            'Para ello, recibirás un correo con un enlace que te permirá acceder al sistema. Una vez dentro tendrás que escoger un nombre de usuario y una contraseña que te servirán en adelante para poder acceder a la aplicación.',
            'Para cualquier duda puedes hacer uso de nuestro formulario de contacto en el menú. '
            ],
        ],
        [
            'label' => 'Sobre Nosotros',
            'content' => [
                'Un proyecto para el curso de Academia Alpe Programación en entornos web',
                'ENCAN'
            ],
        ],
    ]
]);
?>
        </div>
    </div>

</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use amass\panel\Panel;

$this->title = 'Contacto';
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): 

        Panel::begin([
            'headerTitle' => 'Grupos',
            'footer' => false,
            'type' => Panel::TYPE_INFO
        ]);
        echo 'Gracias por contactar con nosotros. En breve nos pondremos en contacto contigo.';
        Panel::end();?>

    <?php else: ?>

        <p class='text-center'>
Utiliza este formulario para transmitirnos tus dudas, sugerirnos ideas o ponerte en contacto con nosotros para lo que necesites. Gracias
        </p>

        <div class="row">
            <div class="col-xs-12 col-sm-6 col-sm-offset-3">

<?php Panel::begin([
    'headerTitle' => 'Login',
    'footer' => false,
    'type' => Panel::TYPE_INFO
]);?>
                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Enviar', ['class' => 'btn btn-primary pull-right', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

<?php Panel::end();?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use amass\panel\Panel;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

<?php Panel::begin([
    'headerTitle' => 'Error',
    'footer' => false,
    'type' => Panel::TYPE_WARNING
]);?>
    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        Ha ocurrido un error mientras el servidor web estaba intentando procesar tu petición.
    </p>
    <p>
        Por favor, contacta con nosotros si crees que esun error del servidor.
    </p>
<p>Gracias</p>

<?php Panel::end();?>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Mercurio mensajería';
?>
<div class="site-index container">

    <div class="body-content row">
    
        <div class="col-xs-12 col-sm-6 jumbotron">
            <h1>Mercurio</h1>
            <p class="lead text-center">Sistema de mensajería para tu Empresa.</p>
         </div>

        <div class="col-sm-6 col-xs-12">
            <div class="thumbnail">
                 <img src=<?= Url::to("@web/imgs/mercurio.jpg")?> alt="mercurio el mensajero de los dioses">
            </div>
        </div>
    </div>


</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use amass\panel\Panel;

$this->title = 'Acceso';
?>
<div class="row site-login">
<div class="col-sm-6 col-sm-offset-3 col-xs-12">

<?php Panel::begin([
    'headerTitle' => 'Login',
    'footer' => false,
    'type' => Panel::TYPE_INFO
]);?>
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Rellena el formulario para acceder al sistema:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-sm-8\">{input}</div>\n<div class=\"col-sm-8 col-sm-offset-4\">{error}</div>",
            'labelOptions' => ['class' => 'col-sm-4 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-sm-offset-1 col-sm-7\">{input} {label}</div>\n<div class=\"col-sm-12\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-8 col-lg-4 col-xs-12">
                <?= Html::submitButton('Entrar', ['class' => 'btn btn-primary btn-block', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); 
Panel::end();?>
</div>
</div>